---
# tasks file for common
- name: Stop Apache2
  service:
    state: stopped
    name: apache2

- name: Install common apt-packages
  apt:
    name: "{{ item }}"
    state: installed
    update_cache: yes
  with_items:
    - htop
    - telnet
    - net-tools
    - ntp
    - git

- name: Set timezone
  timezone:
    name: Europe/Paris

- name: Create app group
  group:
    name: app
    state: present

- name: Create app user
  user:
    name: app
    append: yes
    comment: "user app"
    uid: 1040
    group: app
