---

# tasks file for common
- name: Install mySQL
  apt:
      name: "{{ item }}"
      state: installed
      with_items:
        - mysql

- name: Copy .my.cnf file with root password credentials
  template: src=templates/.my.cnf dest=/etc/mysql/my.cnf owner=root mode=0600

- name: Update mysql root password for all root accounts
  mysql_user: name=root host={{item}} password={{mysql_root_password}}
  with_items:
    - 127.0.0.1
    - ::1
    - localhost